import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportExportData {
  resolutionByLevel: Array<{
    level: string;
    tickets_handled: number;
    session_count: number;
    avg_session_seconds: number;
    total_seconds: number;
  }>;
  workload: Array<{
    id: string;
    name: string;
    department: string;
    designation?: string;
    level: string;
    availability: string;
    status: string;
    active_tickets: number;
    completed_tickets: number;
    avg_resolution_seconds: number;
  }>;
  escalations: {
    transitionMatrix?: Array<{ from_level: string; to_level: string; count: number }>;
    topReasons?: Array<{ reason: string; count: number }>;
  } | null;
  generatedBy?: string;
}

export function formatReportSeconds(sec?: number): string {
  if (!sec || sec <= 0) return '0m';
  const hours = Math.floor(sec / 3600);
  const minutes = Math.round((sec % 3600) / 60);
  if (hours > 0) {
    return `${hours}h ${minutes}m`;
  }
  return `${minutes}m`;
}

export function getReportTimestamp(): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}`;
}

export function getFormattedDateTime(): string {
  const now = new Date();
  return now.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

/**
 * Exports actual report metrics into a formatted multi-sheet Excel (.xlsx) file.
 */
export async function exportReportToExcel(data: ReportExportData): Promise<void> {
  const wb = XLSX.utils.book_new();
  const timestamp = getFormattedDateTime();

  // 1. Summary Sheet
  const totalTransfers = data.escalations?.transitionMatrix?.reduce((acc, curr) => acc + (curr.count || 0), 0) || 0;
  const summaryRows = [
    ['KANVTECH SERVICE MANAGEMENT PLATFORM'],
    ['OPERATIONS & SLA PERFORMANCE REPORT'],
    [''],
    ['Report Metadata', 'Value'],
    ['Generated Date & Time', timestamp],
    ['Generated By', data.generatedBy || 'System Administrator'],
    ['Total Support Specialists Evaluated', data.workload?.length || 0],
    ['Support Tiers Evaluated', data.resolutionByLevel?.length || 0],
    ['Total Escalation Transfers', totalTransfers],
    ['Export Format', 'Microsoft Excel (.xlsx)'],
    [''],
    ['Confidential — For Internal Operations Use Only'],
  ];
  const summaryWs = XLSX.utils.aoa_to_sheet(summaryRows);
  summaryWs['!cols'] = [{ wch: 35 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, summaryWs, 'Overview');

  // 2. Resolution Time by Level Sheet
  const resRows: any[][] = [
    ['Support Tier Level', 'Tickets Handled', 'Total Work Sessions', 'Average Session Duration', 'Cumulative Time Invested (Seconds)', 'Cumulative Time Formatted'],
  ];
  if (!data.resolutionByLevel || data.resolutionByLevel.length === 0) {
    resRows.push(['No data available', '-', '-', '-', '-', '-']);
  } else {
    data.resolutionByLevel.forEach((r) => {
      resRows.push([
        `${r.level} Specialist`,
        r.tickets_handled || 0,
        r.session_count || 0,
        formatReportSeconds(Math.round(r.avg_session_seconds || 0)),
        r.total_seconds || 0,
        formatReportSeconds(r.total_seconds || 0),
      ]);
    });
  }
  const resWs = XLSX.utils.aoa_to_sheet(resRows);
  resWs['!cols'] = [{ wch: 22 }, { wch: 18 }, { wch: 20 }, { wch: 26 }, { wch: 32 }, { wch: 25 }];
  XLSX.utils.book_append_sheet(wb, resWs, 'Resolution by Tier');

  // 3. Specialist Workload Sheet
  const workloadRows: any[][] = [
    ['Employee ID', 'Employee Name', 'Support Tier', 'Department', 'Designation Title', 'Currently Active Tickets', 'Completed Tickets', 'Avg Resolution Time', 'Availability Status', 'Account Status'],
  ];
  if (!data.workload || data.workload.length === 0) {
    workloadRows.push(['No data available', '-', '-', '-', '-', '-', '-', '-', '-', '-']);
  } else {
    data.workload.forEach((emp) => {
      workloadRows.push([
        emp.id,
        emp.name,
        emp.level,
        emp.department || 'General',
        emp.designation || `${emp.level} Specialist`,
        emp.active_tickets || 0,
        emp.completed_tickets || 0,
        formatReportSeconds(Math.round(emp.avg_resolution_seconds || 0)),
        emp.availability || 'AVAILABLE',
        emp.status || 'ACTIVE',
      ]);
    });
  }
  const workloadWs = XLSX.utils.aoa_to_sheet(workloadRows);
  workloadWs['!cols'] = [{ wch: 15 }, { wch: 24 }, { wch: 14 }, { wch: 20 }, { wch: 26 }, { wch: 24 }, { wch: 18 }, { wch: 22 }, { wch: 18 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, workloadWs, 'Specialist Workload');

  // 4. Escalation Flow Telemetry Sheet
  const escRows: any[][] = [
    ['Tier Transfer Volumes'],
    ['Source Support Tier', 'Destination Support Tier', 'Total Transfer Volume'],
  ];
  const matrix = data.escalations?.transitionMatrix || [];
  if (matrix.length === 0) {
    escRows.push(['No transfer data available', '-', '-']);
  } else {
    matrix.forEach((m) => {
      escRows.push([m.from_level, m.to_level, m.count || 0]);
    });
  }

  escRows.push(['']);
  escRows.push(['Leading Escalation Triggers & Reasons']);
  escRows.push(['Escalation Reason / Category', 'Logged Frequency Count']);

  const topReasons = data.escalations?.topReasons || [];
  if (topReasons.length === 0) {
    escRows.push(['No escalation reasons logged', '-']);
  } else {
    topReasons.forEach((r) => {
      escRows.push([r.reason || 'General Escalation', r.count || 0]);
    });
  }

  const escWs = XLSX.utils.aoa_to_sheet(escRows);
  escWs['!cols'] = [{ wch: 35 }, { wch: 30 }, { wch: 25 }];
  XLSX.utils.book_append_sheet(wb, escWs, 'Escalation Telemetry');

  // Trigger download in browser
  const filename = `kanvtech_operations_sla_report_${getReportTimestamp()}.xlsx`;
  XLSX.writeFile(wb, filename);
}

/**
 * Exports actual report metrics into a styled enterprise PDF (.pdf) document.
 */
export async function exportReportToPdf(data: ReportExportData): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const timestamp = getFormattedDateTime();
  const primaryColor = [11, 59, 96] as [number, number, number]; // #0b3b60
  const secondaryColor = [2, 132, 199] as [number, number, number]; // #0284c7
  const darkTextColor = [15, 23, 42] as [number, number, number]; // #0f172a
  const mutedTextColor = [100, 116, 139] as [number, number, number]; // #64748b

  // --- HEADER BANNER ---
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 24, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('KANVTECH SERVICE MANAGEMENT PLATFORM', 14, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(224, 242, 254);
  doc.text('Operations, Resolution Telemetry & Specialist Workload Report', 14, 18);

  // Metadata ribbon
  doc.setFillColor(248, 250, 252);
  doc.rect(14, 28, 182, 14, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, 28, 182, 14, 'S');

  doc.setFontSize(8.5);
  doc.setTextColor(...darkTextColor);
  doc.setFont('helvetica', 'bold');
  doc.text('Generated At:', 18, 36);
  doc.setFont('helvetica', 'normal');
  doc.text(timestamp, 40, 36);

  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', 105, 36);
  doc.setFont('helvetica', 'normal');
  doc.text(data.generatedBy || 'System Administrator', 128, 36);

  let currentY = 48;

  // --- SECTION 1: Resolution Time by Support Level ---
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...primaryColor);
  doc.text('1. Resolution Time by Support Level (L1, L2, L3)', 14, currentY);
  currentY += 4;

  const resTableData =
    data.resolutionByLevel && data.resolutionByLevel.length > 0
      ? data.resolutionByLevel.map((r) => [
          `${r.level} Specialist`,
          `${r.tickets_handled || 0} tickets`,
          `${r.session_count || 0} sessions`,
          formatReportSeconds(Math.round(r.avg_session_seconds || 0)),
          formatReportSeconds(r.total_seconds || 0),
        ])
      : [['No completed work sessions recorded yet.', '-', '-', '-', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Tier Level', 'Tickets Handled', 'Total Work Sessions', 'Avg Session Duration', 'Cumulative Time Invested']],
    body: resTableData,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: darkTextColor,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  currentY = (doc as any).lastAutoTable.finalY + 10;

  // --- SECTION 2: Specialist Workload & Performance Ranking ---
  if (currentY > 230) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...primaryColor);
  doc.text('2. Specialist Workload & Performance Ranking', 14, currentY);
  currentY += 4;

  const workloadTableData =
    data.workload && data.workload.length > 0
      ? data.workload.map((e) => [
          e.name,
          e.id,
          e.level,
          e.department || 'General',
          `${e.active_tickets || 0} active`,
          `${e.completed_tickets || 0} resolved`,
          formatReportSeconds(Math.round(e.avg_resolution_seconds || 0)),
          e.availability,
        ])
      : [['No specialist workload data available.', '-', '-', '-', '-', '-', '-', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Employee Name', 'ID', 'Tier', 'Department', 'Active Tickets', 'Resolved', 'Avg Resolution Time', 'Availability']],
    body: workloadTableData,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: darkTextColor,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  currentY = (doc as any).lastAutoTable.finalY + 10;

  // --- SECTION 3: Escalation Flow Telemetry ---
  if (currentY > 210) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...primaryColor);
  doc.text('3. Escalation Flow Telemetry', 14, currentY);
  currentY += 4;

  // Tier Transfer Volumes Table
  const matrix = data.escalations?.transitionMatrix || [];
  const matrixTableData =
    matrix.length > 0
      ? matrix.map((m) => [`${m.from_level} ➔ ${m.to_level}`, `${m.count} transfers`])
      : [['No escalation transitions recorded yet.', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Tier Transfer Flow', 'Transfer Volume']],
    body: matrixTableData,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: {
      fillColor: secondaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: darkTextColor,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  currentY = (doc as any).lastAutoTable.finalY + 6;

  // Top Reasons Table
  if (currentY > 240) {
    doc.addPage();
    currentY = 20;
  }

  const topReasons = data.escalations?.topReasons || [];
  const reasonsTableData =
    topReasons.length > 0
      ? topReasons.map((r) => [r.reason || 'General Escalation', `${r.count} tickets`])
      : [['No escalation reasons logged yet.', '-']];

  autoTable(doc, {
    startY: currentY,
    head: [['Leading Escalation Trigger / Reason', 'Frequency Count']],
    body: reasonsTableData,
    margin: { left: 14, right: 14 },
    theme: 'grid',
    headStyles: {
      fillColor: secondaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: darkTextColor,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  // --- FOOTER FOR ALL PAGES ---
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...mutedTextColor);
    doc.text('Kanvtech Service Management Platform • Confidential Operations Report', 14, 290);
    doc.text(`Page ${i} of ${totalPages}`, 196, 290, { align: 'right' });
  }

  // Trigger download in browser
  const filename = `kanvtech_operations_sla_report_${getReportTimestamp()}.pdf`;
  doc.save(filename);
}
